structure HolbuildBuiltinManifests =
struct

val holdir_manifest_name = "builtin:HOLDIR"

val holdir_manifest_text =
  String.concatWith "\n"
    ["# Built-in manifest for the reserved HOLDIR dependency.",
     "# Users select the root HOL tree with --holdir, HOLBUILD_HOLDIR, or HOLDIR;",
     "# no HOLDIR manifest/shim file is required.",
     "",
     "[holbuild]",
     "schema = 1",
     "",
     "[project]",
     "name = \"HOLDIR\"",
     "version = \"builtin-bootstrap-sketch\"",
     "",
     "[build]",
     "members = [",
     "  \"src/0\",",
     "  \"src/1\",",
     "  \"src/AI\",",
     "  \"src/Boolify\",",
     "  \"src/HolQbf\",",
     "  \"src/HolSat\",",
     "  \"src/HolSmt\",",
     "  \"src/IndDef\",",
     "  \"src/TeX\",",
     "  \"src/algebra\",",
     "  \"src/bag\",",
     "  \"src/basicProof\",",
     "  \"src/bool\",",
     "  \"src/boss\",",
     "  \"src/coalgebras\",",
     "  \"src/combin\",",
     "  \"src/compute\",",
     "  \"src/coretypes\",",
     "  \"src/datatype\",",
     "  \"src/emit\",",
     "  \"src/finite_maps\",",
     "  \"src/float\",",
     "  \"src/floating-point\",",
     "  \"src/hol88\",",
     "  \"src/holyhammer\",",
     "  \"src/integer\",",
     "  \"src/list\",",
     "  \"src/lite\",",
     "  \"src/marker\",",
     "  \"src/meson\",",
     "  \"src/metis\",",
     "  \"src/monad\",",
     "  \"src/n-bit\",",
     "  \"src/num\",",
     "  \"src/opentheory\",",
     "  \"src/parallel_builds\",",
     "  \"src/parse\",",
     "  \"src/pattern_matches\",",
     "  \"src/pfl\",",
     "  \"src/portableML\",",
     "  \"src/postkernel\",",
     "  \"src/pred_set\",",
     "  \"src/prekernel\",",
     "  \"src/probability\",",
     "  \"src/proofman\",",
     "  \"src/q\",",
     "  \"src/quantHeuristics\",",
     "  \"src/quotient\",",
     "  \"src/rational\",",
     "  \"src/real\",",
     "  \"src/refute\",",
     "  \"src/relation\",",
     "  \"src/res_quan\",",
     "  \"src/search\",",
     "  \"src/simp\",",
     "  \"src/sort\",",
     "  \"src/string\",",
     "  \"src/tactictoe\",",
     "  \"src/taut\",",
     "  \"src/tfl\",",
     "  \"src/thm\",",
     "  \"src/tracing\",",
     "  \"src/transfer\",",
     "  \"src/unwind\",",
     "  \"src/update\",",
     "]",
     "exclude = [",
     "  \"*/selftest.sml\",",
     "  \"*/test.sml\",",
     "  \"*/tests/*\",",
     "  \"*/theory_tests/*\",",
     "  \"*/examples/*\",",
     "  \"*/Manual/*\",",
     "  \"src/emit/MLton/*\",",
     "  \"src/portableML/mlton/*\",",
     "  \"src/portableML/mosml/*\",",
     "  \"src/tracing/no/*\",",
     "  \"src/num/reduce/conv-old/*\",",
     "]",
     ""]

end
