structure HolbuildToolchain =
struct

structure Path = OS.Path
structure FS = OS.FileSys

type t = {holdir : string}

exception Error of string

fun executable {holdir} parts =
  List.foldl (fn (part, acc) => Path.concat(acc, part)) holdir parts

fun hol tc = executable tc ["bin", "hol"]
fun holmake tc = executable tc ["bin", "Holmake"]
fun base_state tc = executable tc ["bin", "hol.state"]

fun quote s =
  "'" ^ String.translate (fn #"'" => "'\\''" | c => str c) s ^ "'"

fun command argv = String.concatWith " " (map quote argv)

fun success status = OS.Process.isSuccess status

fun timing_field text =
  String.translate (fn #"\t" => " " | #"\n" => " " | c => str c) text

fun timing_line {kind, argv, output, status, start, finish} =
  let
    val ms = Time.toMilliseconds (Time.-(finish, start))
    val fields =
      ["tool", "kind=" ^ timing_field kind,
       "status=" ^ (if success status then "ok" else "fail"),
       "ms=" ^ LargeInt.toString ms,
       "argc=" ^ Int.toString (length argv),
       "argv0=" ^ timing_field (case argv of [] => "" | first :: _ => first)] @
      (case output of NONE => [] | SOME path => ["output=" ^ timing_field path])
  in
    String.concatWith "\t" fields ^ "\n"
  end

fun append_timing entry =
  case OS.Process.getEnv "HOLBUILD_TIMING_LOG" of
      NONE => ()
    | SOME path =>
        let val out = TextIO.openAppend path
        in TextIO.output(out, entry); TextIO.closeOut out end
        handle _ => ()

fun phase_line {name, status, start, finish} =
  String.concatWith "\t"
    ["phase",
     "name=" ^ timing_field name,
     "status=" ^ timing_field status,
     "ms=" ^ LargeInt.toString (Time.toMilliseconds (Time.-(finish, start)))] ^ "\n"

fun time_phase name f =
  let val start = Time.now ()
  in
    (let
       val result = f ()
       val finish = Time.now ()
       val _ = append_timing (phase_line {name = name, status = "ok", start = start, finish = finish})
     in
       result
     end)
    handle e =>
      let
        val finish = Time.now ()
        val _ = append_timing (phase_line {name = name, status = "fail", start = start, finish = finish})
      in
        raise e
      end
  end

fun timed_system kind argv output run =
  let
    val start = Time.now ()
    val status = run ()
    val finish = Time.now ()
    val _ = append_timing (timing_line {kind = kind, argv = argv, output = output,
                                        status = status, start = start, finish = finish})
  in
    status
  end

fun run argv =
  timed_system "run" argv NONE (fn () => OS.Process.system (command argv))

fun run_in_dir dir argv =
  timed_system "run_in_dir" argv NONE
    (fn () => OS.Process.system ("cd " ^ quote dir ^ " && " ^ command argv))

fun run_in_dir_to_file dir argv output =
  timed_system "run_in_dir_to_file" argv (SOME output)
    (fn () => OS.Process.system ("cd " ^ quote dir ^ " && " ^ command argv ^
                                 " > " ^ quote output ^ " 2>&1"))

fun ensure_dir path =
  if path = "" orelse path = "." then ()
  else if FS.access(path, []) handle OS.SysErr _ => false then ()
  else (ensure_dir (Path.dir path); FS.mkDir path handle OS.SysErr _ => ())

fun ensure_parent path = ensure_dir (Path.dir path)

fun readable path = FS.access(path, [FS.A_READ]) handle OS.SysErr _ => false

fun require_readable path =
  if readable path then () else raise Error ("required toolchain file not readable: " ^ path)

fun hash_text text =
  let
    val tmp = FS.tmpName ()
    val out = TextIO.openOut tmp
    val _ = TextIO.output(out, text)
    val _ = TextIO.closeOut out
    val hash = SHA1_ML.sha1_file {filename = tmp}
    val _ = FS.remove tmp handle OS.SysErr _ => ()
  in
    hash
  end

fun file_hash path = (require_readable path; HolbuildHash.file_sha1 path)

fun toolchain_key tc =
  hash_text
    (String.concatWith "\n"
       ["holbuild-toolchain-v1",
        "hol=" ^ file_hash (hol tc),
        "base_state=" ^ file_hash (base_state tc)] ^ "\n")

fun sml_string s =
  "\"" ^ String.translate
    (fn #"\\" => "\\\\"
      | #"\"" => "\\\""
      | #"\n" => "\\n"
      | #"\t" => "\\t"
      | c => str c) s ^ "\""

fun write_run_context (project : HolbuildProject.t) =
  let
    val root = #root project
    val hol_dir = Path.concat(root, ".holbuild")
    val context = Path.concat(hol_dir, "holbuild-run-context.sml")
    val _ = ensure_dir hol_dir
    val out = TextIO.openOut context
      handle e => raise Error ("could not write " ^ context ^ ": " ^ General.exnMessage e)
    fun line s = TextIO.output(out, s ^ "\n")
  in
    line "(* generated by holbuild; safe to delete *)";
    line "val _ = ();";
    TextIO.closeOut out;
    context
  end

end
