structure HolbuildToolchain =
struct

structure Path = OS.Path
structure FS = OS.FileSys

type t = {holdir : string}

exception Error of string

fun executable {holdir} parts =
  List.foldl (fn (part, acc) => Path.concat(acc, part)) holdir parts

fun hol tc = executable tc ["bin", "hol"]
fun holmake tc = executable tc ["bin", "Holmake"]

fun quote s =
  "'" ^ String.translate (fn #"'" => "'\\''" | c => str c) s ^ "'"

fun command argv = String.concatWith " " (map quote argv)

fun run argv = OS.Process.system (command argv)

fun run_in_dir dir argv =
  OS.Process.system ("cd " ^ quote dir ^ " && " ^ command argv)

fun success status = OS.Process.isSuccess status

fun ensure_dir path =
  if FS.access(path, []) handle OS.SysErr _ => false then ()
  else FS.mkDir path

fun sml_string s =
  "\"" ^ String.translate
    (fn #"\\" => "\\\\"
      | #"\"" => "\\\""
      | #"\n" => "\\n"
      | #"\t" => "\\t"
      | c => str c) s ^ "\""

fun write_run_context project =
  let
    val root = #root project
    val hol_dir = Path.concat(root, ".hol")
    val context = Path.concat(hol_dir, "holbuild-run-context.sml")
    val includes = map (HolbuildProject.abs_include project) (#includes project)
    val _ = ensure_dir hol_dir
    val out = TextIO.openOut context
      handle e => raise Error ("could not write " ^ context ^ ": " ^ General.exnMessage e)
    fun line s = TextIO.output(out, s ^ "\n")
  in
    line "(* generated by holbuild; safe to delete *)";
    line ("val _ = Meta.loadPath := [" ^
          String.concatWith ", " (map sml_string includes) ^
          "] @ !Meta.loadPath");
    TextIO.closeOut out;
    context
  end

end
